#!/bin/bash
# Quick reference commands for Tower of Hanoi RL

echo "=========================================="
echo "  Tower of Hanoi - Quick Commands"
echo "=========================================="
echo ""
echo "🔹 Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "🔹 Interactive launcher:"
echo "   ./start.sh"
echo ""
echo "🔹 Demo (optimal solution):"
echo "   python main.py demo"
echo ""
echo "🔹 Train a model:"
echo "   python main.py train"
echo "   python main.py train --episodes 500 --show-every 5"
echo ""
echo "🔹 Test trained model:"
echo "   python main.py test"
echo ""
echo "🔹 Help:"
echo "   python main.py --help"
echo "   cat README.md"
echo "   cat SETUP.md"
echo ""
echo "=========================================="
